baseURL = "https://poopbits.com/"
languageCode = "en-us"
theme = "poopbits"
enableGitInfo = "true"
paginate = 8
# disableKinds = ["taxonomyTerm"]

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Poopbits"
    socialNetworks = [
      ["itch.io", "fab fa-itch-io", "https://poopbits.itch.io"],
      ["Discord", "fab fa-discord", "https://discord.gg/t7vd2NT"],
      ["Twitter", "fab fa-twitter", "https://twitter.com/poopbits"],
      ["Facebook", "fab fa-facebook", "https://facebook.com/poopbits"],
      ["Instagram", "fab fa-instagram", "https://instagram.com/poopbits"],
      ["Mastodon", "fab fa-mastodon", "https://mastodon.social/@poopbits"],
      ["Twitch", "fab fa-twitch", "https://twitch.com/poopbits"],
      ["RSS", "fa fa-rss", "/index.xml"],
    ]

    [languages.en.permalinks]
      tags = "/blog/tags/:slug"
      author = "/authors/:slug"
      blog = "/blog/:slug"
      game = "/games/:slug"

    [languages.en.params]
      dateFormat = "01-02-2006"
      homePath = "/"
      copyright = "Copyright &copy; 2012-2020 Poopbits<br>Content on this site is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/'>(cc) by-nc-nd 4.0 license</a>"

      [languages.en.menu]
        [[languages.en.menu.nav]]
          name = "Games"
          pre = "fas fa-fw fa-gamepad"
          title = "Games"
          url = "/games"
          weight = 1

        [[languages.en.menu.nav]]
          name = "Blog"
          pre = "fas fa-fw fa-blog"
          title = "Blog"
          url = "/blog"
          weight = 2

        [[languages.en.menu.nav]]
          name = "Chat"
          pre = "fab fa-fw fa-discord"
          title = "Join us on Discord"
          url = "/chat"
          weight = 3

        [[languages.en.menu.nav]]
          name = "About"
          pre = "fas fa-fw fa-info-circle"
          title = "About"
          url = "/about"
          weight = 4


  [languages.es]
    languageName = "Español"
    weight = 2
    title = "Poopbits"
    socialNetworks = [
      ["itch.io", "fab fa-itch-io", "https://poopbits.itch.io"],
      ["Discord", "fab fa-discord", "https://discord.gg/t7vd2NT"],
      ["Twitter", "fab fa-twitter", "https://twitter.com/poopbits"],
      ["Facebook", "fab fa-facebook", "https://facebook.com/poopbits"],
      ["Instagram", "fab fa-instagram", "https://instagram.com/poopbits"],
      ["Mastodon", "fab fa-mastodon", "https://mastodon.social/@poopbits"],
      ["Twitch", "fab fa-twitch", "https://twitch.com/poopbits"],
      ["RSS", "fa fa-rss", "/es/index.xml"],
    ]

    [languages.es.permalinks]
      tags = "/blog/etiquetas/:slug"
      author = "/blog/autores/:slug"
      blog = "/blog/:slug"
      game = "/videojuegos/:slug"

    [languages.es.params]
      dateFormat = "02/01/2006"
      homePath = "/es"
      copyright = "Derechos de autor &copy; 2012-2020 Poopbits<br>El contenido de este sitio está licenciado bajo <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/deed.es'>(cc) by-nc-nd 4.0 license</a>"

    [languages.es.menu]
      [[languages.es.menu.nav]]
        name = "Videojuegos"
        pre = "fas fa-fw fa-gamepad"
        title = "Videojuegos"
        url = "/es/videojuegos"
        weight = 1

      [[languages.es.menu.nav]]
        name = "Blog"
        pre = "fas fa-fw fa-blog"
        title = "Blog"
        url = "/es/blog"
        weight = 2

      [[languages.es.menu.nav]]
        name = "Chat"
        pre = "fab fa-fw fa-discord"
        title = "Únete a nosotros en Discord"
        url = "/es/chat"
        weight = 3

      [[languages.es.menu.nav]]
        name = "Acerca"
        pre = "fas fa-fw fa-info-circle"
        title = "Acerca"
        url = "/es/acerca"
        weight = 4


  [languages.eo]
    languageName = "Esperanto"
    weight = 2
    title = "Poopbits"
    socialNetworks = [
      ["itch.io", "fab fa-itch-io", "https://poopbits.itch.io"],
      ["Discord", "fab fa-discord", "https://discord.gg/t7vd2NT"],
      ["Twitter", "fab fa-twitter", "https://twitter.com/poopbits"],
      ["Facebook", "fab fa-facebook", "https://facebook.com/poopbits"],
      ["Instagram", "fab fa-instagram", "https://instagram.com/poopbits"],
      ["Mastodon", "fab fa-mastodon", "https://mastodon.social/@poopbits"],
      ["Twitch", "fab fa-twitch", "https://twitch.com/poopbits"],
      ["RSS", "fa fa-rss", "/eo/index.xml"],
    ]

    [languages.eo.permalinks]
      tags = "/blogo/etikedoj/:slug"
      author = "/blogo/aŭtoroj/:slug"
      blog = "/blogo/:slug"
      game = "/videoludoj/:slug"

    [languages.eo.params]
      dateFormat = "02/01/2006"
      homePath = "/eo"
      copyright = "Kopirajto &copy; 2012-2020 Poopbits<br>El ĉi tiu enhavo estas licencita sub <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/deed.eo'>(cc) by-nc-nd 4.0 permesilo</a>"

    [languages.eo.menu]
      [[languages.eo.menu.nav]]
        name = "Videoludoj"
        pre = "fas fa-fw fa-gamepad"
        title = "Videoludoj"
        url = "/eo/videoludoj"
        weight = 1

      [[languages.eo.menu.nav]]
        name = "Blogo"
        pre = "fas fa-fw fa-blog"
        title = "Blogo"
        url = "/eo/blogo"
        weight = 2

      [[languages.eo.menu.nav]]
        name = "Babilo"
        pre = "fab fa-fw fa-discord"
        title = "Aligŭ al ni ĉe Discord"
        url = "/eo/babilo"
        weight = 3

      [[languages.eo.menu.nav]]
        name = "Pri"
        pre = "fas fa-fw fa-info-circle"
        title = "Pri"
        url = "/eo/pri"
        weight = 4


[params]
  showAuthors = false
  gitRepository = "https://gitlab.com/poopbits/poopbits.gitlab.io"
  thumbnailSize = "80x80"
  thumbnailOGSize = "200x200"
  googleAnalytics = "UA-168777548-1"
  favicon = "/images/favicon.gif"
  logo = "/images/poopbits.gif"
  logoHover = "/images/poopbits_animated.gif"
  logoWidth = "141px"
  logoHeight = "39px"

[Taxonomies]
  tag = "tags"
  author = "authors"
  blog = "blogs"
