baseURL = "https://poopbits.com/"
languageCode = "en-us"
title = "Poopbits"
theme = "poopbits"
enableGitInfo = "true"
paginate = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  showAuthors = false
  gitRepository = "https://gitlab.com/poopbits/poopbits.com"
  copyright = "Copyright &copy; 2012-2020 <a href='/about'>Juan Colacelli</a><br>Content on this site is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/'>(cc) by-nc-nd 4.0 license</a>"
  thumbnailSize = "80x80"
  thumbnailOGSize = "200x200"
  googleAnalytics = "UA-168777548-1"
  logo = "/images/poopbits.png"

[Taxonomies]
  tag = "tags"
  author = "authors"
  gamedev = "gamedevs"
  general = "generals"

[Permalinks]
  tags = "/tags/:slug"
  authors = "/authors/:slug"
  gamedev = "/gamedev/:slug"
  general = "/general/:slug"
  tutorials = "/tutorials/:slug"

[menu]
  [[menu.nav]]
    name = "Gamedev"
    title = "Game development"
    url = "/gamedev"
    weight = 1

  [[menu.nav]]
    name = "Tutorials"
    title = "Tutorials"
    url = "/tutorials"
    weight = 2

  [[menu.nav]]
    name = "About"
    title = "About me"
    url = "/about"
    weight = 3
