baseURL = "https://juancolacelli.com/"
languageCode = "en-us"
title = "Juan Colacelli's personal site"
theme = "elefantoj"

[params]
  copyright = "Copyright (c) Juan Colacelli 2012-2020"
  highlightJsTheme = "gruvbox-dark"

[Taxonomies]
  tag = "tags"

[Permalinks]
  blog = "/blog/:slug"
  page = "/:slug"
  tags = "/tags/:slug"

[menu]
  [[menu.nav]]
    name = "Juan's site"
    title = "cd /"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    title = "Just me writing and writing..."
    url = "/blog"
    weight = 2
  [[menu.nav]]
    name = "#gamedev"
    title = "My articles about game development"
    url = "/tags/gamedev"
    weight = 3
  [[menu.nav]]
    name = "About"
    title = "My personal ad"
    url = "/about"
    weight = 4
