baseURL = "https://poopbits.com/"
languageCode = "en-us"
title = "Poopbits"
theme = "poopbits"
enableGitInfo = "true"
paginate = 8

[markup.goldmark.renderer]
  unsafe = true

[params]
  showAuthors = false
  gitRepository = "https://gitlab.com/poopbits/poopbits.com"
  copyright = "Copyright &copy; 2012-2020 <a href='/about'>Juan Colacelli</a><br>Content on this site is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/'>(cc) by-nc-nd 4.0 license</a>"
  thumbnailSize = "80x80"
  thumbnailOGSize = "200x200"
  googleAnalytics = "UA-168777548-1"
  logo = "/images/poopbits.png"
  socialNetworks = [
    ["itch.io", "https://poopbits.itch.io"],
    ["Discord", "https://discord.gg/t7vd2NT"],
    ["Twitter", "https://twitter.com/poopbits"],
    ["Facebook", "https://facebook.com/poopbits"],
    ["Mastodon", "https://mastodon.social/@poopbits"],
    ["Patreon", "https://patreon.com/juancolacelli"],
  ]

[Taxonomies]
  tag = "tags"
  author = "authors"
  gamedev = "gamedevs"
  general = "generals"

[Permalinks]
  tags = "/tags/:slug"
  authors = "/authors/:slug"
  gamedev = "/gamedev/:slug"
  general = "/general/:slug"
  tutorials = "/tutorials/:slug"

[menu]
  [[menu.nav]]
    name = "DROID7"
    title = "Escape or die, it's your choice"
    url = "/droid7"
    weight = 1

  [[menu.nav]]
    name = "Gamedev"
    title = "Game development"
    url = "/gamedev"
    weight = 2

  [[menu.nav]]
    name = "Tutorials"
    title = "Tutorials"
    url = "/tutorials"
    weight = 3

  [[menu.nav]]
    name = "About"
    title = "About"
    url = "/about"
    weight = 4

