baseURL = "https://juancolacelli.com/"
languageCode = "en-us"
theme = "juancolacelli"
removePathAccents = true
enableEmoji = true
enableGitInfo = "true"
paginate = 8
# disableKinds = ["taxonomyTerm"]

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Juan Colacelli"
    socialNetworks = [
      ["itch.io", "https://juancolacelli.itch.io"],
      ["Twitter", "https://twitter.com/juancolacelli"],
      ["Mastodon", "https://mastodon.gamedev.place/@juancolacelli"],
      ["Twitch", "https://twitch.com/juancolacelli"],
      ["YouTube", "https://youtube.com/juancolacelli"],
      ["RSS", "/index.xml"],
    ]

    [languages.en.permalinks]
      tags = "/blog/tags/:slug"
      author = "/authors/:slug"
      blog = "/blog/:slug"
      game = "/games/:slug"

    [languages.en.params]
      dateFormat = "01-02-2006"
      homePath = "/"
      copyright = "Copyright &copy; 2012-2021 Juan Colacelli<br>Content on this site is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/'>(cc) by-nc-nd 4.0 license</a>"

      [languages.en.menu]
        [[languages.en.menu.nav]]
          name = "Games"
          title = "Games"
          url = "/games"
          weight = 1

        [[languages.en.menu.nav]]
          name = "Blog"
          title = "Blog"
          url = "/blog"
          weight = 2

        [[languages.en.menu.nav]]
          name = "Chat"
          title = "Join us on Discord"
          url = "/chat"
          weight = 3

        [[languages.en.menu.nav]]
          name = "About"
          title = "About"
          url = "/about"
          weight = 4


  [languages.es]
    languageName = "Español"
    weight = 2
    title = "Juan Colacelli"
    socialNetworks = [
      ["itch.io", "https://juancolacelli.itch.io"],
      ["Twitter", "https://twitter.com/juancolacelli"],
      ["Mastodon", "https://mastodon.gamedev.place/@juancolacelli"],
      ["Twitch", "https://twitch.com/juancolacelli"],
      ["YouTube", "https://youtube.com/juancolacelli"],
      ["RSS", "fa fa-rss", "/es/index.xml"],
    ]

    [languages.es.permalinks]
      tags = "/blog/etiquetas/:slug"
      author = "/blog/autores/:slug"
      blog = "/blog/:slug"
      game = "/videojuegos/:slug"

    [languages.es.params]
      dateFormat = "02/01/2006"
      homePath = "/es"
      copyright = "Derechos de autor &copy; 2012-2021 Juan Colacelli<br>El contenido de este sitio está licenciado bajo <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/deed.es'>(cc) by-nc-nd 4.0 license</a>"

    [languages.es.menu]
      [[languages.es.menu.nav]]
        name = "Videojuegos"
        title = "Videojuegos"
        url = "/es/videojuegos"
        weight = 1

      [[languages.es.menu.nav]]
        name = "Blog"
        title = "Blog"
        url = "/es/blog"
        weight = 2

      [[languages.es.menu.nav]]
        name = "Chat"
        title = "Únete a nosotros en Discord"
        url = "/es/chat"
        weight = 3

      [[languages.es.menu.nav]]
        name = "Acerca"
        title = "Acerca"
        url = "/es/acerca"
        weight = 4


  [languages.eo]
    languageName = "Esperanto"
    weight = 2
    title = "Juan Colacelli"
    socialNetworks = [
      ["itch.io", "https://juancolacelli.itch.io"],
      ["Twitter", "https://twitter.com/juancolacelli"],
      ["Mastodon", "https://mastodon.gamedev.place/@juancolacelli"],
      ["Twitch", "https://twitch.com/juancolacelli"],
      ["YouTube", "https://youtube.com/juancolacelli"],
      ["RSS", "/eo/index.xml"],
    ]

    [languages.eo.permalinks]
      tags = "/blogo/etikedoj/:slug"
      author = "/blogo/aŭtoroj/:slug"
      blog = "/blogo/:slug"
      game = "/videoludoj/:slug"

    [languages.eo.params]
      dateFormat = "02/01/2006"
      homePath = "/eo"
      copyright = "Kopirajto &copy; 2012-2021 Juan Colacelli<br>El ĉi tiu enhavo estas licencita sub <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/deed.eo'>(cc) by-nc-nd 4.0 permesilo</a>"

    [languages.eo.menu]
      [[languages.eo.menu.nav]]
        name = "Videoludoj"
        title = "Videoludoj"
        url = "/eo/videoludoj"
        weight = 1

      [[languages.eo.menu.nav]]
        name = "Blogo"
        title = "Blogo"
        url = "/eo/blogo"
        weight = 2

      [[languages.eo.menu.nav]]
        name = "Babilo"
        title = "Aligŭ al ni ĉe Discord"
        url = "/eo/babilo"
        weight = 3

      [[languages.eo.menu.nav]]
        name = "Pri"
        title = "Pri"
        url = "/eo/pri"
        weight = 4


[params]
  showAuthors = false
  gitRepository = "https://gitlab.com/juancolacelli/juancolacelli.gitlab.io"
  thumbnailSize = "80x80"
  thumbnailOGSize = "200x200"
  googleAnalytics = "G-38S870CD65"
  favicon = "/images/favicon.png"
  logoWidth = "192px"
  logoHeight = "27px"

[Taxonomies]
  tag = "tags"
  author = "authors"
  blog = "blogs"
