baseURL = "https://colacelli.com/"
languageCode = "en-us"
title = "Juan Colacelli's personal site"
theme = "elefantoj"

[params]
  copyright = "Copyright © 2020 Juan Colacelli"
  highlightJsTheme = "gruvbox-dark"

[Permalinks]
  blog = "/blog/:slug"
  page = "/:slug"

[menu]
  [[menu.nav]]
    name = "JC's site"
    title = "Home page"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    title = "All my blog posts"
    url = "/blog"
    weight = 2
  [[menu.nav]]
    name = "About"
    title = "My former personal add"
    url = "/about"
    weight = 3
