baseURL = "https://juancolacelli.com/"
languageCode = "en-us"
title = "Juan Colacelli's personal site"
theme = "elefantoj"

[params]
  copyright = "Copyright © 2020 Juan Colacelli"
  highlightJsTheme = "gruvbox-dark"

[Permalinks]
  blog = "/blog/:slug"
  page = "/:slug"

[menu]
  [[menu.nav]]
    name = "Juan's site"
    title = "cd /"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    title = "Just me writing and writing..."
    url = "/blog"
    weight = 2
  [[menu.nav]]
    name = "About"
    title = "My personal ad"
    url = "/about"
    weight = 3
