baseURL = "https://colacelli.com/"
languageCode = "en-us"
title = "Juan Colacelli's personal site"
theme = "elefantoj"

[params]
  sitename = "Juan Colacelli's personal site"
  copyright = "Copyright © 2020 Juan Colacelli"

  backgroundColor = "white"
  primaryColor = "black"
  accentColor = "teal"

  fontFamily = "sans-serif"

  highlightJsTheme = "gruvbox-dark"

[Permalinks]
  blog = "/blog/:slug"
  page = "/:slug"

[menu]
  [[menu.nav]]
    name = "Home"
    title = "Home page"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    title = "All my blog posts"
    url = "/blog"
    weight = 2
  [[menu.nav]]
    name = "About"
    title = "My former personal add"
    url = "/about"
    weight = 3
