baseURL = "https://juancolacelli.com/"
languageCode = "en-us"
theme = "elefantoj"
removePathAccents = true
enableEmoji = true
enableGitInfo = "true"
paginate = 8
disableKinds = ["taxonomyTerm"]

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Juan Colacelli's Blog"
    socialNetworks = [
      ["Twitter", "https://twitter.com/juancolacelli"],
      ["Instagram", "https://instagram.com/juancolacelli"],
      ["YouTube", "https://youtube.com/@juancolacelli"],
    ]
    supportNetworks = [
      ["Be a Patreon", "https://patreon.com/juancolacelli"],
      ["Donate with PayPal", "https://www.paypal.com/donate/?hosted_button_id=BV262GXBGA7ZQ"]
    ]

    [languages.en.permalinks]
      tags = "/blog/tags/:slug"
      games = "/blog/games/:slug"
      author = "/authors/:slug"
      blog = "/blog/:slug"
      game = "/:slug"

    [languages.en.params]
      dateFormat = "01-02-2006"
      homePath = "/"
      copyright = "Copyright &copy; 2012-2023 <a href='/about'>Juan Colacelli</a><br>Content on this site is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/'>(cc) by-nc-nd 4.0 license</a>"

    [languages.en.menu]
      [[languages.en.menu.nav]]
        name = "Blog"
        title = "Dear diary..."
        url = "/blog"
        weight = 1

      [[languages.en.menu.nav]]
        name = "Games"
        title = "My games"
        url = "/games"
        weight = 2

      [[languages.en.menu.nav]]
        name = "Projects"
        title = "Other projects"
        url = "/projects"
        weight = 3

      [[languages.en.menu.nav]]
        name = "Chat"
        title = "Join us on Discord"
        url = "/chat"
        weight = 4

      [[languages.en.menu.nav]]
        name = "Patreons"
        title = "People supporting me"
        url = "/patreons"
        weight = 5

      [[languages.en.menu.nav]]
        name = "About"
        title = "Who am I?"
        url = "/about"
        weight = 6

    [[languages.en.games]]
      id = "droid7"
      name = "DROID7"
      description = "Escape or die, it's your choice"
      genre = "Platformer"
      thumbnail = "/games/droid7/thumbnail.png"
      url = "/games/droid7"
      platforms = ["Mac", "PC", "Linux"]

    [[languages.en.games]]
      id = "escapepod"
      name = "Escape Pod"
      description = "Release date: TBD"
      genre = "Shooter"
      thumbnail = "/games/escapepod/thumbnail.png"
      url = ""
      platforms = ["Mac", "PC", "Linux"]

    [[languages.en.games]]
      id = "memomemo"
      name = "Memo Memo"
      description = "Improve your memory matching cards"
      genre = "Cards"
      thumbnail = "/games/memomemo/thumbnail.png"
      url = "/games/memomemo"
      platforms = ["Browser"]

    [[languages.en.games]]
      id = "floppydisk"
      name = "Floppy Disk"
      description = "Just a floppy disk flying..."
      genre = "Platformer"
      thumbnail = "/games/floppydisk/thumbnail.png"
      url = "/games/floppydisk"
      platforms = ["Browser"]


  [languages.es]
    languageName = "Español"
    weight = 2
    title = "Blog de Juan Colacelli"
    socialNetworks = [
      ["Twitter", "https://twitter.com/juancolacelli"],
      ["Instagram", "https://instagram.com/juancolacelli"],
      ["YouTube", "https://youtube.com/@juancolacelli"],
    ]

    [languages.es.permalinks]
      tags = "/blog/etiquetas/:slug"
      games = "/blog/videojuegos/:slug"
      author = "/blog/autores/:slug"
      blog = "/blog/:slug"
      game = "/videojuegos/:slug"

    [languages.es.params]
      dateFormat = "02/01/2006"
      homePath = "/es"
      copyright = "Derechos de autor &copy; 2012-2023 <a href='/es/acerca'>Juan Colacelli</a><br>El contenido de este sitio está licenciado bajo <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/deed.es'>(cc) by-nc-nd 4.0 license</a>"

    [languages.es.menu]
      [[languages.es.menu.nav]]
        name = "Videojuegos"
        title = "Videojuegos"
        url = "/es/videojuegos"
        weight = 1

      [[languages.es.menu.nav]]
        name = "Blog"
        title = "Blog"
        url = "/es/blog"
        weight = 2

      [[languages.es.menu.nav]]
        name = "Chat"
        title = "Únete a nosotros en Discord"
        url = "/es/chat"
        weight = 3

      [[languages.es.menu.nav]]
        name = "Acerca"
        title = "Acerca"
        url = "/es/acerca"
        weight = 4

    [[languages.es.games]]
      id = "droid7"
      name = "DROID7"
      genre = "Plataforma"
      description = "Escapa o muere, es tu decisión"
      thumbnail = "/droid7/thumbnail.png"
      url = "/es/videojuegos/droid7"
      platforms = ["Mac", "PC", "Linux"]

    [[languages.es.games]]
      id = "escapepod"
      name = "Escape Pod"
      description = "Fecha de lanzamiento: TBD"
      genre = "Disparos"
      thumbnail = "/games/escapepod/thumbnail.png"
      url = ""
      platforms = ["Mac", "PC", "Linux"]


  [languages.eo]
    languageName = "Esperanto"
    weight = 2
    title = "Juan Colacelli Blogo"
    socialNetworks = [
      ["Twitter", "https://twitter.com/juancolacelli"],
      ["Instagram", "https://instagram.com/juancolacelli"],
      ["YouTube", "https://youtube.com/@juancolacelli"],
    ]

    [languages.eo.permalinks]
      tags = "/blogo/etikedoj/:slug"
      games = "/blog/videoludoj/:slug"
      author = "/blogo/aŭtoroj/:slug"
      blog = "/blogo/:slug"
      game = "/videoludoj/:slug"

    [languages.eo.params]
      dateFormat = "02/01/2006"
      homePath = "/eo"
      copyright = "Kopirajto &copy; 2012-2023 <a href='/eo/pri'>Juan Colacelli</a><br>El ĉi tiu enhavo estas licencita sub <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/deed.eo'>(cc) by-nc-nd 4.0 permesilo</a>"

    [languages.eo.menu]
      [[languages.eo.menu.nav]]
        name = "Videoludoj"
        title = "Videoludoj"
        url = "/eo/videoludoj"
        weight = 1

      [[languages.eo.menu.nav]]
        name = "Blogo"
        title = "Blogo"
        url = "/eo/blogo"
        weight = 2

      [[languages.eo.menu.nav]]
        name = "Babilo"
        title = "Aligŭ al ni ĉe Discord"
        url = "/eo/babilo"
        weight = 3

      [[languages.eo.menu.nav]]
        name = "Pri"
        title = "Pri"
        url = "/eo/pri"
        weight = 4

    [[languages.eo.games]]
      id = "droid7"
      name = "DROID7"
      genre = "Platformo"
      description = "Eskapi aŭ morti estas via elekto"
      thumbnail = "/droid7/thumbnail.png"
      url = "/eo/videoludoj/droid7"
      platforms = ["Mac", "PC", "Linux"]

    [[languages.eo.games]]
      id = "escapepod"
      name = "Escape Pod"
      description = "Eldondato: TBD"
      genre = "Pafisto"
      thumbnail = "/games/escapepod/thumbnail.png"
      url = ""
      platforms = ["Mac", "PC", "Linux"]


[params]
  itchio = "https://juancolacelli.itch.io"
  patreon = "https://patreon.com/juancolacelli"
  discord = "https://discord.gg/pixel-cave-608242475043389480"
  gitRepository = "https://gitlab.com/juancolacelli/juancolacelli.com"
  showAuthors = false
  defaultThumbnail = "/images/thumbnail.png"
  thumbnailSize = "80x80"
  thumbnailOGSize = "200x200"
  googleAnalytics = "G-38S870CD65"
  favicon = "/images/favicon.png"
  logo = "/images/logo1.png"
  logoHover = "/images/logo2.png"
  logoWidth = "40px"
  logoHeight = "40px"

[Taxonomies]
  tag = "tags"
  author = "authors"
  blog = "blogs"
  game = "games"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"
