baseURL = "https://juancolacelli.com/"
languageCode = "en-us"
title = "Juan Colacelli's personal site"
theme = "elefantoj"
enableGitInfo = "true"

[params]
  gitRepository = "https://gitlab.com/juancolacelli/juancolacelli.com"
  copyright = "Copyright &copy; 2012-2020 Juan Colacelli<br>Content on this site is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/'>(cc) by-nc-nd 4.0 license</a>"

[Taxonomies]
  tag = "tags"

[Permalinks]
  blog = "/blog/:slug"
  page = "/:slug"
  tags = "/tags/:slug"

[menu]
  [[menu.nav]]
    name = "Blog"
    title = "Just me writing and writing..."
    url = "/blog"
    weight = 1
  [[menu.nav]]
    name = "#gamedev"
    title = "My articles about game development"
    url = "/tags/gamedev"
    weight = 2
  [[menu.nav]]
    name = "About"
    title = "My personal ad"
    url = "/about"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
